name: Pull Request Build

concurrency: 
    group: ${{ github.head_ref }}
    cancel-in-progress: true

on:
    pull_request: 
        branches: [ main ]
  
jobs:
    changes:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: read
      outputs:
        github-client: ${{ steps.detected-changes.outputs.github-client }}
        sources: ${{ steps.detected-changes.outputs.sources }}
      steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: detected-changes
        with:
          filters: |
            github-client:
              - 'Sources/GitHubClient/**'
            sources:
              - 'Sources/**'
              - 'Tests/**'
              - Package.swift
              - Package.resolved
              - .github/workflows/**/*.yml

    check-for-api-changes:
        needs: [changes]
        name: Check if GitHub API client or models need to be regenerated
        runs-on: ubuntu-latest 
        steps:
            - uses: swift-actions/setup-swift@3aed395c5397f62deb91d8fe7af1418a9ae4d16f
              with:
                swift-version: "5.10"
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
            - name: Generate openapi and check if generated code has changed
              if: ${{ needs.changes.outputs.github-client == 'true' }}
              run: make generate-github-client && (git diff --quiet -- Sources/GitHubClient || (echo "run 'make generate-github-client' and commit the changes " && exit 1))

    run-tests:
        needs: [changes]
        name: Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-13
                swift-version: ["5.9", "5.10"]
        steps:
            - uses: swift-actions/setup-swift@3aed395c5397f62deb91d8fe7af1418a9ae4d16f
              with:
                swift-version: ${{ matrix.swift-version }}
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
            - name: Run tests
              if: ${{ needs.changes.outputs.sources == 'true' }}
              run: swift test
