name: Pull Request Build

concurrency: 
    group: ${{ github.head_ref }}
    cancel-in-progress: true

on:
    pull_request: 
        branches: [ main ]

jobs:
    check-for-api-changes:
        name: Check if GitHub API client or models need to be regenerated
        runs-on: ubuntu-latest 
        steps:
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: 5.9
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            - name: Generate openapi
              run: make generate-github-client
            - name: Check if it changed
              run: git pull $GITHUB_BASE_REF && git diff --quiet $GITHUB_REF $GITHUB_BASE_REF -- Sources/GitHubClient || (echo "run 'make generate-github-client' and commit the changes " && exit 1)

    run-tests:
        name: Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-13
                swift-version: ["5.9"]
        steps:
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: ${{ matrix.swift-version }}
            - uses: actions/checkout@v4
            - name: Run tests
              run: swift test
            
