name: Build Agamotto

on:
  push:
    branches: [ main, romain/test-upload-to-s3 ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.9
      - uses: actions/checkout@v4
      # - name: Run Tests
      #   run: swift test
      - name: Build binary
        id: build-bin
        run: swift build --product agamotto -c release
      
      - name: Create archive
        id: create-archive
        run: tar -czf agamotto.tar.gz $(swift build --show-bin-path -c release)/agamotto

      - name: Upload to S3
        run: aws s3 cp agamotto.tar.gz s3://palleas-storage/homebrew/agamotto-${{ github.run_number }}.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
