name: Build Agamotto

on:
  push:
    branches:
      - main

env:
  RELEASE_VERSION: 0.1.${{ github.run_number }}

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: swift-actions/setup-swift@3aed395c5397f62deb91d8fe7af1418a9ae4d16f
        with:
          swift-version: "5.10"
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Run Tests
        run: swift test

      - name: Build binary
        run: swift build --product agamotto -c release
      
      - name: Run binary
        run: $(swift build --show-bin-path -c release)/agamotto --help

      - name: Create archive
        id: create-archive
        run: tar -czf agamotto.tar.gz -C $(swift build --show-bin-path -c release) agamotto

      - name: Create pre-release
        run: gh release create --prerelease --generate-notes $RELEASE_VERSION agamotto.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}