name: Build Agamotto

on:
  push:
    branches: [ main, romain/test-upload-to-s3 ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.9
      - uses: actions/checkout@v4
      # - name: Run Tests
      #   run: swift test
      - name: Build binary
        id: build-bin
        run: |
          swift build --product agamotto -c release
          echo "::set-output name=path-to-bin::$(swift build --show-bin-path -c release)/agamotto"
      
      - name: Create archive
        id: create-archive
        run: |
          tar -czf agamotto-${{ github.run_number }}.tar.gz ${{ steps.build-bin.outputs.path-to-bin }}
          echo "::set-output name=path-to-archive::agamotto-${{ github.run_number }}.tar.gz"

      - name: Upload to S3
        run: aws s3 sync ${{ steps.create-archive.outputs.path-to-archive }} s3://palleas-storage/homebrew/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
