name: Build Agamotto

on:
  push:
    branches:
      - main

env:
  RELEASE_VERSION: 0.1.${{ github.run_number }}

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: 5.9
      - uses: actions/checkout@v4

      - name: Run Tests
        run: swift test

      - name: Build binary
        run: swift build --product agamotto -c release
      
      - name: Run binary
        run: $(swift build --show-bin-path -c release)/agamotto --help

      - name: Create archive
        id: create-archive
        run: tar -czf agamotto.tar.gz -C $(swift build --show-bin-path -c release) agamotto

      - name: Upload to S3
        run: aws s3 cp --acl public-read agamotto.tar.gz s3://palleas-storage/homebrew/agamotto-$RELEASE_VERSION.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: Create pre-release
        run: gh release create --prerelease --generate-notes $RELEASE_VERSION agamotto.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}